all:
  children:
    master:
      hosts:
        octo:
          ansible_host: 192.168.0.172
    workers:
      hosts:
        adam:
          ansible_host: 192.168.0.181
        eve:
          ansible_host: 192.168.0.182
