all:
  hosts:
    master:
      # define VM IP for main node:
      ansible_host: 192.168.0.172
      join_url: ""
  children:
    workers:
      # define list of other nodes below (you can skip ansible_host if you provide IP instead of common name)
      hosts:
        adam:
          ansible_host: 192.168.0.181
        eve:
          ansible_host: 192.168.0.182
