all:
  hosts:
    master:
      ansible_host: 192.168.0.172
      join_url: ""
  children:
    workers:
      hosts:
        adam:
          ansible_host: 192.168.0.181
        eve:
          ansible_host: 192.168.0.182
