---
- name: initiate master and start dashboard
  become: true
  hosts: master
  roles:
    - master

- name: connect remaining nodes to cluster
  become: true
  hosts: workers
  roles:
    - workers
