---
- name: install microk8s and start services
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - common

# - name: initiate master
#   hosts: master
#   roles:
#     - master

# - name: join workers to cluster
#   hosts: workers
#   roles:
#     - workers
