- name: enable EPEL Repository
  dnf:
    name: epel-release
    state: latest

- name: install snap
  yum:
    name: snapd
    state: latest

- name: enable snapd.socket
  ansible.builtin.systemd:
    name: snapd.socket
    enabled: yes
    state: started
    daemon_reload: yes

- name: enable snap access
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
