- name: Enable EPEL Repository on CentOS 8
  dnf:
    name: epel-release
    state: latest

- name: centos install snap
  yum:
    name: snapd
    state: latest

- name: enable snapd.socket
  ansible.builtin.systemd:
    name: snapd.socket
    enabled: yes

- name: enable snap access
  command:
    "ln -s /var/lib/snapd/snap /snap"

# - name: centos install microk8s
#   community.general.snap:
#     name: microk8s
#     classic: yes
