- name: install snap and microk8s
  import_tasks: centos.yaml
  when: ansible_facts['os_family']|lower == 'redhat'
- import_tasks: ubuntu.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- name: start services
  ansible.builtin.systemd:
    name: microk8s
    state: started
    enabled: yes
    masked: no
