- name: install snap
  import_tasks: centos.yaml
  when: ansible_facts['os_family']|lower == 'redhat'
- import_tasks: ubuntu.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- getent:
    database: passwd
    key: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
    split: ":"

- name: enable snap access
  ansible.builtin.file:
    src: "/snap/bin/microk8s"
    dest: "/usr/bin/microk8s"
    state: link

- name: install microk8s
  community.general.snap:
    name: microk8s
    classic: yes

- name: Add current user to microk8s group
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
    append: yes
    groups: microk8s

- name: Recursively change ownership of a ~/.kube
  ansible.builtin.file:
    path: "{{ getent_passwd[ansible_env.SUDO_USER][4] }}/.kube"
    state: directory
    recurse: yes
    owner: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Add kubectl alias for current user
  lineinfile:
    path: "{{ getent_passwd[ansible_env.SUDO_USER][4] }}/.bashrc"
    line: "alias kubectl='microk8s kubectl'"
    owner: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
    regexp: "'^alias kubectl='microk8s kubectl'$"
    state: present
    insertafter: EOF
    create: yes

- name: start microk8s
  become: false
  ansible.builtin.command: "microk8s start"
