- name: enable master modules
  become: false
  ansible.builtin.command: "microk8s enable dashboard dns ingress"

- name: open cluster for connection
  become: false
  ansible.builtin.command: "microk8s add-node --token-ttl 20"
  register: add_node
  notify:
    - "initiate dashboard"

- name: Create persistent var
  set_fact:
    join_url: "{{ add_node.stdout_lines[1] }}"



